### ISSUE TITLE
Parser won't work

### ISSUE THREAD

**Issue by alternativex** [mwkling/umdmusic-downloader#3]
I get this error

Downloading data from: http://www.umdmusic.com/default.asp?Lang=English&Chart=D
Traceback (most recent call last):
  File "downloader.py", line 51, in <module>
    main()
  File "downloader.py", line 32, in main
    for row in main_table.tbody.children:
AttributeError: 'NoneType' object has no attribute 'children'

**Comment by alternativex** [comment]
I was not able to use the html5lib see error

Traceback (most recent call last):
  File "downloader.py", line 51, in <module>
    main()
  File "downloader.py", line 15, in main
    soup = BeautifulSoup(html, "html5lib")
  File "build/bdist.macosx-10.12-intel/egg/bs4/__init__.py", line 165, in __init__

**Comment by ghost** [comment]
Make sure you have html5lib installed. You can use pip to install it or conda if you are running anaconda
